# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PeazFoLW23vNM8deYmsfcwc8sgPp71Wg
"""

import pandas as pd
from surprise import Dataset, Reader

def load_movie_lens_data(file_path):
    reader = Reader(line_format='user item rating timestamp', sep='\t')
    return Dataset.load_from_file(file_path, reader=reader)

def load_metadata(ratings_path, items_path, users_path):
    ratings = pd.read_csv(ratings_path, sep='\t', names=["user_id", "item_id", "rating", "timestamp"])
    movies = pd.read_csv(items_path, sep='|', encoding='latin-1', names=[
        "item_id", "movie_title", "release_date", "video_release_date", "IMDb_URL",
        "unknown", "Action", "Adventure", "Animation", "Children's", "Comedy", "Crime",
        "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror", "Musical", "Mystery",
        "Romance", "Sci-Fi", "Thriller", "War", "Western"])
    users = pd.read_csv(users_path, sep='|', names=["user_id", "age", "gender", "occupation", "zip_code"])
    return ratings, movies, users