# -*- coding: utf-8 -*-
"""recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PeazFoLW23vNM8deYmsfcwc8sgPp71Wg
"""

from surprise import KNNBasic
from surprise.model_selection import train_test_split
from surprise import accuracy
from collections import defaultdict


def train_cf_model(data, user_based=True):
    trainset, testset = train_test_split(data, test_size=0.2, random_state=42)
    sim_options = {"name": "cosine", "user_based": user_based}
    model = KNNBasic(sim_options=sim_options)
    model.fit(trainset)
    predictions = model.test(testset)
    return model, predictions, testset


def get_top_n(predictions, n=10):
    top_n = defaultdict(list)
    for uid, iid, true_r, est, _ in predictions:
        top_n[uid].append((iid, est))
    for uid, user_ratings in top_n.items():
        user_ratings.sort(key=lambda x: x[1], reverse=True)
        top_n[uid] = user_ratings[:n]
    return top_n